apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-index
  labels:
    app: apache
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Apache</title>
    </head>
    <body>
      <h1>Hallo daar!</h1>
  
    </body>
    </html>
